# Generated by Django 3.2.5 on 2021-07-22 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=6)),
                ('currency_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.IntegerField()),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buy', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buy', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobitex.market')),
            ],
        ),
    ]
