# Generated by Django 3.2.5 on 2021-12-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_buyer_maker',
            new_name='is_bid',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='is_bid',
            new_name='is_buyer_maker',
        ),
    ]
