# Generated by Django 3.2.5 on 2021-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0003_alter_markettrades_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='time',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
