# Generated by Django 3.2.5 on 2021-07-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0004_marketdata_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markettrades',
            unique_together={('market', 'time', 'price', 'volume', 'is_buy')},
        ),
    ]
