# Generated by Django 3.2.5 on 2021-07-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0005_alter_markettrades_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='markettrades',
            name='created_at',
        ),
    ]
