# Generated by Django 3.2.5 on 2021-11-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0006_auto_20210730_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettrades',
            name='time',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
