MARKETS = [
    ('BTC', 'IRT'),
    ('ETH', 'IRT'),
    ('LTC', 'IRT'),
    ('XRP', 'IRT'),
    ('BCH', 'IRT'),
    ('BNB', 'IRT'),
    ('EOS', 'IRT'),
    ('XLM', 'IRT'),
    ('ETC', 'IRT'),
    ('TRX', 'IRT'),
    ('DOGE', 'IRT'),
    ('UNI', 'IRT'),
    ('DAI', 'IRT'),
    ('USDT', 'IRT'),
    ('BTC', 'USDT'),
    ('ETH', 'USDT'),
    ('LTC', 'USDT'),
    ('XRP', 'USDT'),
    ('BCH', 'USDT'),
    ('BNB', 'USDT'),
    ('EOS', 'USDT'),
    ('XLM', 'USDT'),
    ('ETC', 'USDT'),
    ('TRX', 'USDT'),
    ('DOGE', 'USDT'),
    ('UNI', 'USDT'),
    ('DAI', 'USDT'),
]
FEES= {
    'TAKER': .0013,
    'MAKER': .0013,
}
TASK_PERIODS = {
    'nobitex.collect.orders': 10,
    'nobitex.collect.trades': 20,
    'nobitex.store.orders': 60,
    'nobitex.store.trades': 60*2,
}
