# Generated by Django 3.2.5 on 2022-07-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobitex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='market',
        ),
        migrations.AlterField(
            model_name='market',
            name='base_asset',
            field=models.IntegerField(choices=[(-1, 'Irt'), (0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')]),
        ),
        migrations.AlterField(
            model_name='market',
            name='quote_asset',
            field=models.IntegerField(choices=[(-1, 'Irt'), (0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')]),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
