# Generated by Django 3.2.5 on 2022-05-20 20:36

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=8, unique=True)),
                ('futures_name', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_multiplier', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('lot_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('tick_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('index_price_tick_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('max_leverage', models.IntegerField(default=None, null=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SpotMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_min_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('quote_min_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('base_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('quote_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('price_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SpotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='4 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='SpotOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='4 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.futurescontract')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.futurescontract')),
            ],
        ),
    ]
