# Generated by Django 3.2.5 on 2022-01-29 21:27

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=8, unique=True)),
                ('futures_name', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin_data.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin_data.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SpotMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin_data.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kucoin_data.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SpotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='4 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin_data.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='SpotOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin_data.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='4 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin_data.futurescontract')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin_data.futurescontract')),
            ],
        ),
    ]
