# Generated by Django 3.2.5 on 2022-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin_data', '0002_auto_20220220_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurescontract',
            name='index_price_tick_size',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='futurescontract',
            name='lot_multiplier',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='futurescontract',
            name='lot_size',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='futurescontract',
            name='maxLeverage',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='futurescontract',
            name='tick_size',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotmarket',
            name='base_increment',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotmarket',
            name='base_min_size',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotmarket',
            name='price_increment',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotmarket',
            name='quote_increment',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='spotmarket',
            name='quote_min_size',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True),
        ),
    ]
