# Generated by Django 3.2.5 on 2022-02-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin_data', '0003_auto_20220223_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurescontract',
            old_name='maxLeverage',
            new_name='max_leverage',
        ),
    ]
