version: '3.8'

services:

  bookwatch_image:
    build:
      context: ./bookwatch
    image: bookwatch_image

  bookwatch:
    image: bookwatch_image
    command: "python main.py"
    environment:
      - ENV=PROD
    restart: always
    depends_on:
      - bookwatch_redis

  journal_redis:
    image: redis:7.0.4-alpine
    restart: always

  cache_redis:
    image: redis:7.0.4-alpine
    restart: always

  celery_redis:
    image: redis:7.0.4-alpine
    ports:
      - "6479:6379"
    restart: always

  bookwatch_redis:
    image: redis:7.0.4-alpine
    ports:
      - "6579:6379"
    restart: always

  analysisdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=analysisdb
      - POSTGRES_PASSWORD=analysisdb
      - POSTGRES_DB=analysisdb
    volumes:
      - ./configs/analysisdb/002_set_configs.sh:/docker-entrypoint-initdb.d/002_set_configs.sh
      - ./configs/analysisdb/analysisdb.conf:/analysisdb.conf
      - analysisdb_data:/var/lib/postgresql/data/

  analysisdb_pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    environment:
       - DB_USER=analysisdb
       - DB_PASSWORD=analysisdb
       - DB_HOST=analysisdb
       - MAX_CLIENT_CONN=65535
       - DB_NAME=analysisdb
       - AUTH_TYPE=plain
       - POOL_MODE=transaction
       - DEFAULT_POOL_SIZE=896
       - MAX_DB_CONNECTIONS=896
       - ADMIN_USERS=analysisdb
    ports:
      - "5532:5432"
    depends_on:
      - analysisdb

  analysis__image:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    image: analysis__image

  analysis__run_collector:
    image: analysis__image
    command: "./entrypoint.run_collectors.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - journal_redis
      - analysisdb

  analysis__trade_rpc:
    image: analysis__image
    command: "./entrypoint.trade_rpc.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - celery_redis
      - cache_redis
      - analysisdb

  analysis__query_rpc:
    image: analysis__image
    command: "./entrypoint.query_rpc.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - celery_redis
      - analysisdb

  analysis__demo_matcher:
    image: analysis__image
    command: "./entrypoint.demo_matcher.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - cache_redis
      - analysisdb

  bots_image:
    build:
      context: ./bots
    image: bots_image

  bot0:
    image: bots_image
    command: "/app/bot0"
    environment:
      - RPC_REDIS=redis://185.208.175.141:6479/0
      - BOOKWATCH_REDIS_HOST=185.208.175.141:6579
      - BOOKWATCH_REDIS_DB=0
      - ENV=PROD
    restart: always

  bot1:
    image: bots_image
    command: "/app/bot1"
    environment:
      - RPC_REDIS=redis://185.208.175.141:6479/0
      - BOOKWATCH_REDIS_HOST=185.208.175.141:6579
      - BOOKWATCH_REDIS_DB=0
      - ENV=PROD
    restart: always

  jupyter:
    image: jupyter/datascience-notebook
    environment:
      - GRANT_SUDO=yes
      - PASSWORD=asdasdasd
    ports:
      - "8015:8888"
    volumes:
      - jupyterhome:/home/jovyan/
  proxy:
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./v2ray/config/:/etc/v2ray/

volumes:
  analysisdb_data:
  jupyterhome:

