version: '3.8'

services:
  default_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_default
      - POSTGRES_PASSWORD=simpletrader_default
      - POSTGRES_DB=simpletrader_default
    ports:
      - 5431:5432

  timescale_db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5433:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_ts
      - POSTGRES_PASSWORD=simpletrader_ts
      - POSTGRES_DB=simpletrader_ts

volumes:
  postgres_data:
  timescale_data: