version: '3.8'

services:
  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=all
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  bookwatch_image:
    build:
      context: ./bookwatch
    image: bookwatch_image

  bookwatch:
    image: bookwatch_image
    command: "python main.py"
    environment:
      - ENV=PROD
    restart: always
    depends_on:
      - bookwatch_redis

  journal_redis:
    image: redis:7.0.4-alpine
    restart: always

  cache_redis:
    image: redis:7.0.4-alpine
    restart: always

  celery_redis:
    image: redis:7.0.4-alpine
    ports:
      - "6479:6379"
    restart: always

  bookwatch_redis:
    image: redis:7.0.4-alpine
    ports:
      - "6579:6379"
    restart: always

  goapp_base_image:
    build:
      context: ./goapp
      dockerfile: Dockerfile.base_image
    image: goapp_base_image

  bot0_image:
    build:
      context: ./goapp
      dockerfile: Dockerfile.bot0_image
    image: bot0_image

  bot0:
    image: bot0_image
    command: "./bot0"
    # environment:
    #   - BOOKWATCH_REDIS=
    #   - CELERY_REDIS=
    #   - CONFIG_DIR=/sharedconfs/
    # restart: always
    # volumes:
    #   - ./configs/shared/:/sharedconfs/
    # depends_on:
    #   - bookwatch_redis

  analysisdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=analysisdb
      - POSTGRES_PASSWORD=analysisdb
      - POSTGRES_DB=analysisdb
    volumes:
      - analysisdb_data:/var/lib/postgresql/data/

  analysisdb_pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=analysisdb
       - DB_PASSWORD=analysisdb
       - DB_HOST=analysisdb
       - DB_NAME=analysisdb
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,analysisdb
    ports:
      - "5532:5432"
    depends_on:
      - analysisdb

  analysis__image:
    build:
      context: ./analysis
      dockerfile: Dockerfile
    image: analysis__image

  analysis__run_collector:
    image: analysis__image
    command: "./entrypoint.run_collectors.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - journal_redis
      - analysisdb

  analysis__trade_rpc:
    image: analysis__image
    command: "./entrypoint.trade_rpc.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - celery_redis
      - cache_redis
      - analysisdb

  analysis__query_rpc:
    image: analysis__image
    command: "./entrypoint.query_rpc.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - celery_redis
      - analysisdb

  analysis__demo_matcher:
    image: analysis__image
    command: "./entrypoint.demo_matcher.sh"
    restart: always
    environment:
      - DEBUG=0
    depends_on:
      - cache_redis
      - analysisdb

volumes:
  analysisdb_data:
