version: '3.8'

services:
  simpletrader_base_image:
    build:
      context: ./app
      dockerfile: Dockerfile.simpletrader_base_image
    image: simpletrader_base_image

  simpletrader_image:
    build:
      context: ./app
      dockerfile: Dockerfile.simpletrader_image
    image: simpletrader_image

  kucoin__store_trades:
    image: simpletrader_image
    command: "./entrypoint.kucoin_store_trades.sh"
    restart: always
    environment:
      - DEBUG=true
      - TIMESCALE_DB_PASSWORD=simpletrader_ts
      - DEFAULT_DB_PASSWORD=simpletrader_default
    depends_on:
      - journal_redis
      - timescale_db

  kucoin__collect_trades:
    image: simpletrader_image
    command: "./entrypoint.kucoin_collect_trades.sh"
    restart: always
    environment:
      - DEBUG=true
      - TIMESCALE_DB_PASSWORD=simpletrader_ts
      - DEFAULT_DB_PASSWORD=simpletrader_default
    depends_on:
      - journal_redis
      - timescale_db

  nobitex__collect_trades:
    image: simpletrader_image
    command: "./entrypoint.nobitex_collect_trades.sh"
    restart: always
    environment:
      - DEBUG=true
      - TIMESCALE_DB_PASSWORD=simpletrader_ts
      - DEFAULT_DB_PASSWORD=simpletrader_default
    depends_on:
      - journal_redis
      - timescale_db

  journal_redis:
    image: redis
    restart: always

  cache_redis:
    image: redis
    restart: always

  celery_redis:
    image: redis
    restart: always

  default_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_default
      - POSTGRES_PASSWORD=simpletrader_default
      - POSTGRES_DB=simpletrader_default

  timescale_db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    volumes:
      - timescale_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_ts
      - POSTGRES_PASSWORD=simpletrader_ts
      - POSTGRES_DB=simpletrader_ts

volumes:
  postgres_data:
  timescale_data: