# Generated by Django 3.2.5 on 2022-05-22 20:07

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.IntegerField(choices=[(0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')])),
                ('quote_asset', models.IntegerField(choices=[(0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')])),
                ('lot_multiplier', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('lot_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('tick_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('index_price_tick_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('max_leverage', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.IntegerField(choices=[(0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')])),
                ('quote_asset', models.IntegerField(choices=[(0, 'Usdt'), (1, 'Btc'), (2, 'Eth'), (3, 'Ltc'), (4, 'Xrp'), (5, 'Bch'), (6, 'Bnb'), (7, 'Eos'), (8, 'Xlm'), (9, 'Etc'), (10, 'Trx'), (11, 'Doge'), (12, 'Uni'), (13, 'Link'), (14, 'Dot'), (15, 'Aave'), (16, 'Ada'), (17, 'Shib'), (18, 'Ftm'), (19, 'Matic'), (20, 'Axs'), (21, 'Mana'), (22, 'Sand')])),
                ('base_min_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('quote_min_size', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('base_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('quote_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('price_increment', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='SpotOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='12 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.spotmarket')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.futurescontract')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesOrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='12 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_bid', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.futurescontract')),
            ],
        ),
    ]
