# Generated by Django 3.2.5 on 2022-07-05 19:03

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Nobitex'), (2, 'Kucoin Spot'), (3, 'Kucoin Futures')])),
                ('related_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin.market')),
            ],
        ),
        migrations.RemoveField(
            model_name='spotorderbook',
            name='market',
        ),
        migrations.DeleteModel(
            name='FuturesOrderBook',
        ),
        migrations.DeleteModel(
            name='SpotOrderBook',
        ),
    ]
