# Generated by Django 3.2.5 on 2022-07-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin', '0002_auto_20220705_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spottrade',
            name='market',
        ),
        migrations.DeleteModel(
            name='FuturesTrade',
        ),
        migrations.DeleteModel(
            name='SpotTrade',
        ),
    ]
