# Generated by Django 3.2.16 on 2023-02-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='order_uid',
            field=models.UUIDField(db_index=True, default=None, null=True),
        ),
    ]
