from simpletrader.kucoin.models import Asset

MARKETS = [
    (Asset.btc, Asset.irt),
    (Asset.eth, Asset.irt),
    (Asset.ltc, Asset.irt),
    (Asset.xrp, Asset.irt),
    (Asset.bch, Asset.irt),
    (Asset.bnb, Asset.irt),
    (Asset.eos, Asset.irt),
    (Asset.xlm, Asset.irt),
    (Asset.etc, Asset.irt),
    (Asset.trx, Asset.irt),
    (Asset.doge, Asset.irt),
    (Asset.uni, Asset.irt),
    (Asset.aave, Asset.irt),
    (Asset.usdt, Asset.irt),
    (Asset.btc, Asset.usdt),
    (Asset.eth, Asset.usdt),
    (Asset.ltc, Asset.usdt),
    (Asset.xrp, Asset.usdt),
    (Asset.bch, Asset.usdt),
    (Asset.bnb, Asset.usdt),
    (Asset.eos, Asset.usdt),
    (Asset.xlm, Asset.usdt),
    (Asset.etc, Asset.usdt),
    (Asset.trx, Asset.usdt),
    (Asset.doge, Asset.usdt),
    (Asset.uni, Asset.usdt),
    (Asset.aave, Asset.usdt),
]
