# Generated by Django 3.2.5 on 2022-12-01 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0002_auto_20221201_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.SmallIntegerField(db_index=True)),
                ('external_id', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BotSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('to_timestamp', models.DateTimeField()),
                ('is_demo', models.BooleanField(default=True)),
                ('initial_worth', models.DecimalField(decimal_places=16, max_digits=32)),
                ('final_worth', models.DecimalField(decimal_places=16, max_digits=32)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
            ],
        ),
        migrations.CreateModel(
            name='BotStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trader_god.botstatechange')),
            ],
        ),
        migrations.AddIndex(
            model_name='botsummary',
            index=models.Index(fields=['bot', '-from_timestamp'], include=('to_timestamp',), name='a8408d602e31e4934a51d4154'),
        ),
        migrations.AddIndex(
            model_name='botstatechange',
            index=models.Index(fields=['bot', '-created_at'], include=('state',), name='a39e3f290edc1428eb43052a4'),
        ),
    ]
