FROM python:3.9.6-alpine
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN mkdir -p /var/log/simpletrader/

COPY ./entrypoint.kucoin_collect_trades.sh .
RUN chmod +x ./entrypoint.kucoin_collect_trades.sh
COPY . .

CMD ["/usr/src/app/entrypoint.kucoin_collect_trades.sh"]
