version: '3.8'

services:
  default_db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_default
      - POSTGRES_PASSWORD=simpletrader_default
      - POSTGRES_DB=simpletrader_default

  timescale_db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5436:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simpletrader_ts
      - POSTGRES_PASSWORD=simpletrader_ts
      - POSTGRES_DB=simpletrader_ts

  traderdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5437:5432
    volumes:
      - traderdb_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=traderdb
      - POSTGRES_PASSWORD=traderdb
      - POSTGRES_DB=traderdb

volumes:
  postgres_data:
  timescale_data:
  traderdb_data:
