# Generated by Django 3.2.5 on 2022-04-25 18:45

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Spot Trade Entropy'), (2, 'Futures Trade Entropy')])),
                ('period', models.DurationField()),
                ('related_id', models.IntegerField()),
                ('params', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='4 hour')),
                ('values', models.JSONField(default=dict)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucoin_index.measure')),
            ],
        ),
    ]
