# Generated by Django 3.2.5 on 2022-04-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin_index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='timestamp',
            new_name='time',
        ),
    ]
