# Generated by Django 3.2.5 on 2022-05-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin_index', '0002_rename_timestamp_measurement_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('measure', 'time')},
        ),
    ]
