# Generated by Django 3.2.5 on 2022-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kucoin_index', '0003_alter_measurement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='type',
            field=models.IntegerField(choices=[(1, 'Spot Trade Entropy'), (2, 'Futures Trade Entropy'), (3, 'Spot Candle'), (4, 'Futures Candle')]),
        ),
    ]
