# Generated by Django 3.2.5 on 2022-11-11 21:01

from django.db import migrations, models
import django.db.models.deletion
import simpletrader.trader.models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.IntegerField()),
                ('_credentials', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('token', models.CharField(default=simpletrader.trader.models.create_bot_token, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WalletSnapShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('asset_id', models.SmallIntegerField(db_index=True)),
                ('free_balance', models.DecimalField(decimal_places=16, max_digits=32)),
                ('blocked_balance', models.DecimalField(decimal_places=16, max_digits=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=32)),
                ('client_order_id', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True)),
                ('leverage', models.SmallIntegerField(blank=True, default=1)),
                ('exchange_id', models.IntegerField(db_index=True)),
                ('market_id', models.IntegerField(db_index=True)),
                ('status_id', models.IntegerField()),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('price', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('volume', models.DecimalField(decimal_places=16, max_digits=32)),
                ('is_sell', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.account')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=32)),
                ('external_order_id', models.CharField(db_index=True, max_length=32)),
                ('exchange_id', models.IntegerField(db_index=True)),
                ('market_id', models.IntegerField(db_index=True)),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('price', models.DecimalField(decimal_places=16, default=None, max_digits=32, null=True)),
                ('volume', models.DecimalField(decimal_places=16, max_digits=32)),
                ('is_sell', models.BooleanField()),
                ('fee', models.DecimalField(decimal_places=16, max_digits=32)),
                ('fee_asset_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.account')),
            ],
        ),
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.account')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
            ],
            options={
                'unique_together': {('bot', 'account')},
            },
        ),
    ]
