# Generated by Django 4.1 on 2022-10-08 18:36

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSnapShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('free_balance', models.DecimalField(decimal_places=16, max_digits=32)),
                ('blocked_balance', models.DecimalField(decimal_places=16, max_digits=32)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RunSQL('''
-- public.trader_walletsnapshot definition

-- Drop table

-- DROP TABLE public.trader_walletsnapshot;

CREATE TABLE public.trader_walletsnapshot (
	id bigserial NOT NULL,
	"timestamp" timestamptz NOT NULL,
	free_balance numeric(32, 16) NOT NULL,
	blocked_balance numeric(32, 16) NOT NULL,
	account_id int8 NOT NULL,
    asset_id int4 NOT NULL,
	CONSTRAINT trader_walletsnapshot_account_id_4640aa97_fk_trader_account_id FOREIGN KEY (account_id) REFERENCES public.trader_account(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX trader_walletsnapshot_account_id_46409e97 ON public.trader_walletsnapshot USING btree (account_id);
CREATE INDEX trader_walletsnapshot_timestamp_idx ON public.trader_walletsnapshot USING btree ("timestamp" DESC);
CREATE INDEX trader_walletsnapshot_asset_id_ce132r23 ON public.trader_walletsnapshot USING btree (asset_id);

-- Table Triggers

create trigger ts_insert_blocker before
insert
    on
    public.trader_walletsnapshot for each row execute function _timescaledb_internal.insert_blocker();
        '''),

    ]
