# Generated by Django 4.1 on 2022-09-30 18:54

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.SmallIntegerField(db_index=True)),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(interval='24 hour')),
                ('free_balance', models.DecimalField(decimal_places=16, max_digits=32)),
                ('blocked_balance', models.DecimalField(decimal_places=16, max_digits=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.account')),
            ],
        ),
    ]
