# Generated by Django 3.2.5 on 2022-11-19 20:08

from django.db import migrations, models
import simpletrader.trader.models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(default=simpletrader.trader.models.create_bot_token, max_length=16, primary_key=True, serialize=False),
        ),
    ]
