# Generated by Django 3.2.5 on 2022-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='managed',
            new_name='is_managed',
        ),
        migrations.AddField(
            model_name='account',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
