# Generated by Django 3.2.5 on 2022-11-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20221119_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botaccount',
            unique_together=set(),
        ),
    ]
