# Generated by Django 4.1 on 2022-10-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_balancerecord'),
        ('trader', '0002_walletsnapshot'),
    ]

    operations = [
    ]
