# Generated by Django 3.2.5 on 2022-12-01 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20221201_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trader.bot'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('bot', 'exchange_id', 'is_fake')},
        ),
        migrations.DeleteModel(
            name='BotAccount',
        ),
    ]
