# Generated by Django 3.2.5 on 2022-08-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleStick_05m',
            fields=[
                ('start_time', models.DateTimeField()),
                ('period', models.DurationField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'db_table': 'indices_candlestick_05m',
                'managed': False,
            },
        ),
        migrations.RunSQL('''
            CREATE MATERIALIZED VIEW indices_candlestick_05m
            WITH (timescaledb.continuous) AS
            SELECT market_id,
            0 as id,
            time_bucket(INTERVAL '5 min', time) AS start_time,
            INTERVAL '5 min' as period,
            first(price, time) as open,
            last(price, time) as close,
            MIN(price),
            MAX(price)
            FROM kucoin_trade kt
            group by market_id , start_time
        '''),
        migrations.RunSQL('''
        SELECT add_continuous_aggregate_policy(
            'indices_candlestick_05m',
            start_offset => INTERVAL '10 min',
            end_offset => INTERVAL '10 second',
            schedule_interval => INTERVAL '5 min'
        );
        '''),
    ]
