# Generated by Django 3.2.16 on 2023-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(),
        ),
    ]
