# Generated by Django 3.2.16 on 2023-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wallet_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_bot_asset_pair',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='account',
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_uid',
            field=models.UUIDField(default='99994715-bc10-442f-85a1-de3a8bad9896'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('account_uid', 'asset'), name='unique_bot_asset_pair'),
        ),
    ]
