# Generated by Django 3.2.16 on 2023-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230210_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(10, 'Demo'), (20, 'Regular'), (30, 'Internal'), (40, 'External')], default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_uid',
            field=models.UUIDField(db_index=True),
        ),
    ]
