# Generated by Django 3.2.16 on 2023-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230212_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(10, 'Demo'), (20, 'Regular'), (30, 'Internal'), (40, 'External')], default=10),
        ),
    ]
