# Generated by Django 3.2.16 on 2023-02-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230220_1526'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='non_negative_free_balance',
        ),
        migrations.RemoveConstraint(
            model_name='wallet',
            name='non_negative_block_balance',
        ),
    ]
