# Generated by Django 3.2.5 on 2022-12-01 11:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.SmallIntegerField()),
                ('exchange_id', models.SmallIntegerField()),
                ('free_balance', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=32)),
                ('blocked_balance', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=32)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('type', models.SmallIntegerField(choices=[(1, 'Block'), (2, 'Gain'), (3, 'Pay')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_wallets.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot_wallets.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_id__isnull', True)), fields=('wallet_id',), name='one_null_parent_only'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('bot', 'asset_id', 'exchange_id'), name='unqibotassetexchange'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('free_balance__gte', 0)), name='walletnonnefreebalance'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('blocked_balance__gte', 0)), name='walletnonnegblockedbalance'),
        ),
    ]
