# Generated by Django 3.2.5 on 2022-11-25 19:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0003_alter_botaccount_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.SmallIntegerField()),
                ('exchange_id', models.SmallIntegerField()),
                ('free_balance', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=32)),
                ('blocked_balance', models.DecimalField(decimal_places=16, default=Decimal('0'), max_digits=32)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.bot')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='24 hour')),
                ('amount', models.DecimalField(decimal_places=16, max_digits=32)),
                ('type', models.SmallIntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_wallets.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('free_balance__gte', 0)), name='wallet_non_negative_free_balance'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('blocked_balance__gte', 0)), name='wallet_non_negative_blocked_balance'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('bot', 'asset_id', 'exchange_id')},
        ),
    ]
