# Generated by Django 3.2.16 on 2023-01-25 08:41

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.IntegerField()),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='6 hour')),
                ('base_amount', models.FloatField()),
                ('quote_amount', models.FloatField()),
                ('is_buyer_maker', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.exchange')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='analysis.asset')),
            ],
        ),
    ]
