# Generated by Django 3.2.16 on 2023-02-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]


    operations = [
        migrations.RemoveField(
            model_name='market',
            name='base_asset',
        ),
        migrations.RemoveField(
            model_name='market',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='market',
            name='quote_asset',
        ),
        migrations.DeleteModel(
            name='Market',
        ),

        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
