version: '3.8'

services:
  analysisdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=analysisdb
      - POSTGRES_PASSWORD=analysisdb
      - POSTGRES_DB=analysisdb


  analysisdb_pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=analysisdb
       - DB_PASSWORD=analysisdb
       - DB_HOST=analysisdb
       - MAX_CLIENT_CONN=65535
       - DB_NAME=analysisdb
       - AUTH_TYPE=plain
       - POOL_MODE=transaction
       - DEFAULT_POOL_SIZE=80
       - MAX_DB_CONNECTIONS=80
       - ADMIN_USERS=analysisdb
    ports:
      - "5536:5432"
    depends_on:
      - analysisdb
