version: '3.8'

services:
  analysisdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=analysisdb
      - POSTGRES_PASSWORD=analysisdb
      - POSTGRES_DB=analysisdb
    volumes:
      - ./postgres/002_set_configs.sh:/docker-entrypoint-initdb.d/002_set_configs.sh
      - ./postgres/analysisdb.conf:/analysisdb.conf

  analysisdb_pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=analysisdb
       - DB_PASSWORD=analysisdb
       - DB_HOST=analysisdb
       - MAX_CLIENT_CONN=65535
       - DB_NAME=analysisdb
       - AUTH_TYPE=plain
       - POOL_MODE=transaction
       - DEFAULT_POOL_SIZE=896
       - MAX_DB_CONNECTIONS=896
       - ADMIN_USERS=analysisdb
    ports:
      - "5536:5432"
    depends_on:
      - analysisdb
