version: '3.8'

services:
  analysisdb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=analysisdb
      - POSTGRES_PASSWORD=analysisdb
      - POSTGRES_DB=analysisdb
